# Generated by Django 4.1.7 on 2023-04-02 00:34

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('home', 'Student')
    Student(name="Joe Silver", email="joe@email.com", document="22342342", phone="00000000").save()

class Migration(migrations.Migration):
    
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
