# Generated by Django 4.1.7 on 2023-04-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("password", models.CharField(default="none", max_length=50)),
                ("first_name", models.CharField(default="none", max_length=255)),
                ("last_name", models.CharField(default="none", max_length=255)),
                ("address", models.CharField(default="", max_length=255)),
                ("Phone", models.CharField(default="xxxxxxxxxx", max_length=10)),
                ("father_name", models.CharField(default="none", max_length=255)),
                ("mother_name", models.CharField(default="none", max_length=255)),
                ("short_bio", models.CharField(default="none", max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "male"), ("F", "female")],
                        default="none",
                        max_length=6,
                    ),
                ),
                (
                    "blood",
                    models.CharField(
                        choices=[
                            ("A-", "A-"),
                            ("A+", "A+"),
                            ("B-", "B-"),
                            ("B+", "B+"),
                            ("AB-", "AB-"),
                            ("AB+", "AB+"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        default="",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Teacher", "Teacher"),
                            ("Parent", "Parent"),
                            ("Admin", "Admin"),
                        ],
                        default="none",
                        max_length=15,
                    ),
                ),
                (
                    "religion",
                    models.CharField(
                        choices=[
                            ("Muslim", "Muslim"),
                            ("Christian", "Christian"),
                            ("Jewish", "Jewish"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ifLogged", models.BooleanField(default=False)),
            ],
        ),
    ]
