# Generated by Django 4.1.7 on 2023-04-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addusers",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="addusers",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="addusers",
            name="Phone",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="addusers",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
