# Generated by Django 4.1.7 on 2023-04-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0002_remove_user_username_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="none", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="none", max_length=128),
        ),
    ]
