# Generated by Django 4.1.4 on 2023-04-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_user_is_active_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='religion',
        ),
    ]
