# Generated by Django 4.1.7 on 2023-04-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0003_alter_addusers_short_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=50)),
                ("ifLogged", models.BooleanField(default=False)),
                ("token", models.CharField(default="", max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="AddUsers",
        ),
    ]
