# Generated by Django 4.1.7 on 2023-04-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0005_alter_user_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="blood",
        ),
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
    ]
