# Generated by Django 4.1.7 on 2023-04-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0006_remove_user_blood_remove_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="father_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="mother_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="short_bio",
            field=models.CharField(max_length=200),
        ),
    ]
