# Generated by Django 4.1.7 on 2023-04-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0007_alter_user_father_name_alter_user_mother_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blood",
            field=models.CharField(
                choices=[
                    ("A-", "A-"),
                    ("A+", "A+"),
                    ("B-", "B-"),
                    ("B+", "B+"),
                    ("AB-", "AB-"),
                    ("AB+", "AB+"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                default="-",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "male"), ("F", "female")], default="-", max_length=6
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="religion",
            field=models.CharField(
                choices=[
                    ("Muslim", "Muslim"),
                    ("Christian", "Christian"),
                    ("Jewish", "Jewish"),
                ],
                default="-",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("teacher", "teacher"),
                    ("Parent", "Parent"),
                    ("Admain", "Admain"),
                ],
                default="-",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="Phone",
            field=models.CharField(default="-", max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(default="-", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="father_name",
            field=models.CharField(default="-", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="-", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="-", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="mother_name",
            field=models.CharField(default="-", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="-", max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="short_bio",
            field=models.CharField(default="-", max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="-", max_length=255),
        ),
    ]
