# Generated by Django 4.1.7 on 2023-04-14 06:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0008_user_blood_user_gender_user_religion_user_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="ifLogged",
            new_name="if_logged",
        ),
        migrations.RemoveField(
            model_name="user",
            name="Phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="blood",
        ),
        migrations.AddField(
            model_name="user",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A-", "A-"),
                    ("A+", "A+"),
                    ("B-", "B-"),
                    ("B+", "B+"),
                    ("AB-", "AB-"),
                    ("AB+", "AB+"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                default="",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="father_name",
            field=models.CharField(default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="", max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="mother_name",
            field=models.CharField(default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="religion",
            field=models.CharField(
                choices=[
                    ("Muslim", "Muslim"),
                    ("Christian", "Christian"),
                    ("Jewish", "Jewish"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="short_bio",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Teacher", "Teacher"),
                    ("Parent", "Parent"),
                    ("Admin", "Admin"),
                ],
                default="",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(default="", max_length=10)),
                ("subject", models.TextField(default="")),
                ("message", models.TextField(default="")),
                (
                    "name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="API.user",
                    ),
                ),
            ],
        ),
    ]
