# Generated by Django 4.1.7 on 2023-04-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0010_alter_contact_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=6
            ),
        ),
    ]
