# Generated by Django 4.1.7 on 2023-04-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0011_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Teacher", "Teacher"),
                    ("Parent", "Parent"),
                    ("Admain", "Admain"),
                ],
                default="",
                max_length=15,
            ),
        ),
    ]
