# Generated by Django 4.1.7 on 2023-04-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0012_alter_user_gender_alter_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="",
                max_length=6,
            ),
        ),
    ]
