# Generated by Django 4.1.7 on 2023-04-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0013_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
