# Generated by Django 4.1.7 on 2023-04-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0015_remove_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
