# Generated by Django 4.1.7 on 2023-04-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0016_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
    ]
