# Generated by Django 4.1.7 on 2023-04-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0017_remove_user_gender_remove_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Teacher", "Teacher"),
                    ("Parent", "Parent"),
                    ("Admain", "Admain"),
                ],
                default="",
                max_length=15,
            ),
        ),
    ]
