# Generated by Django 4.1.4 on 2023-04-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mother_name',
            new_name='MotherName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='religion',
            new_name='Religion',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='short_bio',
            new_name='ShortBio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='Username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='Blood',
            field=models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='FatherName',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='Status',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Parent', 'Parent'), ('Admin', 'Admin')], default='', max_length=15),
        ),
    ]
