# Generated by Django 4.1.4 on 2023-04-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_rename_address_user_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Firstname',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Religion',
            new_name='Religon',
        ),
    ]
